/**
 * Utility to process and correct LaTeX and chemistry formula formatting
 * generated by AI models.
 */

/**
 * Collapses runs of vertical, single-character lines (e.g. spelling out chemical formulas/words)
 * into unified horizontal lines.
 */
function collapseVerticalText(text: string): string {
  if (!text) return text;
  
  const lines = text.split("\n");
  const resultLines: string[] = [];
  let currentRun: string[] = [];
  
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();
    
    // Check if the line is a single character, or a short chemical sub/super (like Cr_2, O_7, etc.)
    const isShort = trimmed.length === 0 || 
                    trimmed.length === 1 || 
                    /^[a-zA-Z0-9_\{\}\^+-]{1,4}$/.test(trimmed);
                    
    if (isShort) {
      currentRun.push(trimmed);
    } else {
      if (currentRun.length >= 5) {
        let collapsed = "";
        for (const char of currentRun) {
          if (char === "") {
            collapsed += " ";
          } else {
            collapsed += char;
          }
        }
        collapsed = collapsed.replace(/\s+/g, " ").trim();
        if (collapsed) {
          resultLines.push(collapsed);
        }
      } else {
        resultLines.push(...currentRun);
      }
      currentRun = [];
      resultLines.push(line);
    }
  }
  
  if (currentRun.length >= 5) {
    let collapsed = "";
    for (const char of currentRun) {
      if (char === "") {
        collapsed += " ";
      } else {
        collapsed += char;
      }
    }
    collapsed = collapsed.replace(/\s+/g, " ").trim();
    if (collapsed) {
      resultLines.push(collapsed);
    }
  } else {
    resultLines.push(...currentRun);
  }
  
  return resultLines.join("\n");
}

/**
 * Merges adjacent math blocks separated only by raw LaTeX/text sequences:
 * e.g., $math1$ raw_latex $math2$ -> $math1 raw_latex math2$
 */
function mergeMismatchedMathBlocks(text: string): string {
  if (!text) return text;
  
  let current = text;
  let previous = "";
  
  const mergeRegex = /\$([^\$]+?)\$\s*([A-Za-z0-9_\{\}\\\s,\(\)\+\-\=\rightarrow\rightleftharpoons\circ\cdot\rightleftharpoons]+?)\s*\$([^\$]+?)\$/g;
  
  while (current !== previous) {
    previous = current;
    current = current.replace(mergeRegex, (match, math1, rawLatex, math2) => {
      if (/[\\_^{}]/.test(rawLatex)) {
        return `$${math1} ${rawLatex} ${math2}$`;
      }
      return match;
    });
  }
  
  return current;
}

/**
 * Replaces matching patterns only when they are outside of math blocks ($...$ or $$...$$).
 */
function replaceOutsideMath(text: string, regex: RegExp, replacement: string | ((match: string, ...args: any[]) => string)): string {
  if (!text) return text;
  const parts = text.split("$");
  for (let i = 0; i < parts.length; i += 2) {
    if (parts[i]) {
      if (typeof replacement === "function") {
        parts[i] = parts[i].replace(regex, replacement as any);
      } else {
        parts[i] = parts[i].replace(regex, replacement);
      }
    }
  }
  return parts.join("$");
}

/**
 * Checks for and repairs common LaTeX/KaTeX issues in AI responses:
 * 1. Unescaped/escaped parentheses inside subscripts (e.g., \)_5 -> )_5).
 * 2. Unescaped chemistry formulas (H2O -> \text{H}_2\text{O}).
 * 3. Thermodynamics terms outside math blocks (e.g., \Delta_f H -> $\Delta_f H$).
 * 4. Mismatched square brackets in complex ions.
 * 5. Chemistry formulas with double subscripts (e.g., \text{NH}_3_4 -> \left(\text{NH}_{3}\right)_{4}).
 * 6. Units like kJ mol^{-1} outside math blocks.
 * 7. KaTeX text mode errors (e.g., \text{g mol^{-1}} where superscripts break text mode).
 */
export function fixLatexFormatting(text: string): string {
  if (!text) return text;

  // Collapse vertical character arrays first
  let fixed = collapseVerticalText(text);

  // 1. Clean up literal escaped/forward-slash newlines
  fixed = fixed.replace(/\\n/g, "\n").replace(/\/n/g, "\n");

  // 2. Fix unescaped/wrongly escaped parentheses in math blocks:
  // e.g. \)_5 -> )_5, \)^{2+} -> )^{2+}, \)_2 -> )_2
  fixed = fixed.replace(/\\\)(?=_[a-zA-Z0-9{}]|\^[a-zA-Z0-9{}]|[\s\+\-\=]|$)/g, ")");
  fixed = fixed.replace(/\\\((?=[a-zA-Z0-9{])/g, "(");
  
  // Replace backslash parentheses inside \text{...} blocks
  // e.g. \text{Co(NH}_3\)_5 -> \text{Co(NH}_3)_5
  fixed = fixed.replace(/(\\text\{[^{}]*)\\\(([^{}]*\})/g, "$1($2");
  fixed = fixed.replace(/(\\text\{[^{}]*)\\\)([^{}]*\})/g, "$1)$2");

  // 3. Fix mismatched outer square brackets for complex chemical ions:
  // e.g., if we see \text{Co(NH}_3)_5\text{Cl}]^{2+} without a starting '[', we can prefix it
  fixed = fixed.replace(/(?<!\[)(?:\\text\{[A-Za-z0-9_]+\}|\b[A-Z][a-z]?)\([A-Za-z0-9_\\\{\}]*\)[A-Za-z0-9_\\\{\}]*\]\^(?:\{[0-9\+\-]+\}|[0-9\+\-])/g, (match) => {
    return "[" + match;
  });

  // 4. Fix incomplete superscripts like \text{Cl}^ or Cl^ at the end of a math expression or word
  fixed = fixed.replace(/\\text\{Cl\}\^(?!\{-|-[0-9]|\+|[0-9])/g, "\\text{Cl}^-");
  fixed = fixed.replace(/\bCl\^(?!\{-|-[0-9]|\+|[0-9])/g, "Cl^-");

  // 5. Convert \( ... \) to $ ... $ and \[ ... \] to $$ ... $$ for inline and block math
  fixed = fixed.replace(/\\\(/g, "$");
  fixed = fixed.replace(/\\\)/g, "$");
  fixed = fixed.replace(/\\\[/g, "$$");
  fixed = fixed.replace(/\\\]/g, "$$");

  // 6. Fix KaTeX text mode errors: \text{... ^ ...} or \text{... _ ...} is invalid in KaTeX.
  // We extract subscripts/superscripts out of the \text{} block.
  // e.g. \text{g mol^{-1}} -> \text{g mol}^{-1}
  for (let iter = 0; iter < 3; iter++) {
    fixed = fixed.replace(/\\text\{([^{}\^]*)\^\{?([^{}]*?)\}?\}/g, "\\text{$1}^{$2}");
    fixed = fixed.replace(/\\text\{([^{}_]*)_\{?([^{}]*?)\}?\}/g, "\\text{$1}_{$2}");
  }

  // 7. Fix chemistry formulas with double subscripts:
  // e.g. \text{NH}_3_4 -> \left(\text{NH}_{3}\right)_{4}
  fixed = fixed.replace(/(\\text\{([A-Za-z0-9_]+)\}|[A-Z][a-z]?)_\{?(\d+)\}?_\{?(\d+)\}?/g, (match, fullGroup, innerText, sub1, sub2) => {
    const symbolText = innerText || fullGroup;
    return `\\left(\\text{${symbolText}}_{${sub1}}\\right)_{${sub2}}`;
  });

  // 8. Support for \ce{...} formatting:
  // If there are \ce{...} occurrences outside of math blocks (not enclosed in $), wrap them in $...$.
  fixed = fixed.replace(/(?<!\$)\\ce\{([^{}]+)\}(?!\$)/g, "$\\ce{$1}$");
  // Clean up if we accidentally created $$...$$ or $...$ boundary issues:
  fixed = fixed.replace(/\$\$+\\ce/g, "$$\\ce");
  fixed = fixed.replace(/ce\{([^{}]+)\}\$\$+/g, "ce{$1}$$");

  // 9. Support for chemical formulas like H2O, CO2, H2SO4, NH3, O2, N2, etc., when written as plain text (e.g. H 2 O or H2O)
  const commonChemicals = [
    { raw: /\bH\s*2\s*O\b/gi, latex: "\\text{H}_2\\text{O}" },
    { raw: /\bC\s*O\s*2\b/gi, latex: "\\text{CO}_2" },
    { raw: /\bO\s*2\b/gi, latex: "\\text{O}_2" },
    { raw: /\bN\s*2\b/gi, latex: "\\text{N}_2" },
    { raw: /\bN\s*H\s*3\b/gi, latex: "\\text{NH}_3" },
    { raw: /\bC\s*H\s*4\b/gi, latex: "\\text{CH}_4" },
    { raw: /\bH\s*2\s*S\s*O\s*4\b/gi, latex: "\\text{H}_2\\text{SO}_4" },
    { raw: /\bH\s*C\s*l\b/gi, latex: "\\text{HCl}" },
    { raw: /\bN\s*a\s*O\s*H\b/gi, latex: "\\text{NaOH}" },
    { raw: /\bN\s*a\s*C\s*l\b/gi, latex: "\\text{NaCl}" },
    { raw: /\bC\s*6\s*H\s*12\s*O\s*6\b/gi, latex: "\\text{C}_6\\text{H}_{12}\\text{O}_6" },
    { raw: /\bC\s*a\s*C\s*O\s*3\b/gi, latex: "\\text{CaCO}_3" },
    { raw: /\bH\s*N\s*O\s*3\b/gi, latex: "\\text{HNO}_3" }
  ];
  
  commonChemicals.forEach(({ raw, latex }) => {
    fixed = replaceOutsideMath(fixed, raw, `$${latex}$`);
  });

  // 10. Fix thermodynamics terms like \Delta_f H^{\circ}(\ce{C_5H_{12}O}) = -210\,\text{kJ mol^{-1}}
  // and make sure they are wrapped in math blocks when outside.
  fixed = replaceOutsideMath(fixed, /\\Delta_[a-zA-Z0-9]?\s*[H|G|S](?:[^\s$]*?)(?=\s|\b|$)/g, (match) => {
    return `$${match}$`;
  });

  // 11. Wrap thermodynamic values with units (e.g., -210 kJ mol^-1 or -210 kJ/mol) when outside of math blocks.
  fixed = replaceOutsideMath(fixed, /([-\d\.]+)\s*(?:kJ|g)\s*(?:mol\^\{-1\}|mol\^-1|\/\s*mol)/g, (match) => {
    const clean = match
      .replace(/kJ\s*mol\^\{-1\}|kJ\s*mol\^-1/g, "\\text{kJ}\\cdot\\text{mol}^{-1}")
      .replace(/g\s*mol\^\{-1\}|g\s*mol\^-1/g, "\\text{g}\\cdot\\text{mol}^{-1}")
      .replace(/kJ\/\s*mol/g, "\\text{kJ/mol}")
      .replace(/g\/\s*mol/g, "\\text{g/mol}");
    return `$${clean}$`;
  });

  // 12. Fix unit formatting like kJ mol$^{-1}$ or mol$^{-1}$ specifically:
  fixed = fixed.replace(/(?:kJ|g)\s*mol\s*\$\^\{-1\}\$/gi, "$\\text{kJ}\\cdot\\text{mol}^{-1}$");
  fixed = fixed.replace(/mol\s*\$\^\{-1\}\$/gi, "$\\text{mol}^{-1}$");

  // Merge split/mismatched adjacent dollar blocks (e.g. $math1$ raw_latex $math2$)
  fixed = mergeMismatchedMathBlocks(fixed);

  // Clean up any duplicate dollars created by multiple wrapping operations
  fixed = fixed.replace(/\$\$+/g, "$$");
  
  // Clean up formatting issues like double-spacing or excess newlines
  fixed = fixed.replace(/\n\s*\n\s*\n+/g, "\n\n");

  return fixed;
}

/**
 * Detects if a question text contains inline options (e.g. 1) Opt1 2) Opt2 ... or (A) OptA (B) OptB ...).
 * If detected, it extracts these options, strips them from the question text, and returns both.
 */
export function extractInlineOptions(text: string): { questionText: string, options: string[] } | null {
  if (!text) return null;

  const patterns = [
    // Style 1: (1) ... (2) ... (3) ... (4) ... or (A) ... (B) ... (C) ... (D) ...
    {
      regex: /[\s\n]*\((1|A)\)\s+([\s\S]*?)[\s\n]*\((2|B)\)\s+([\s\S]*?)[\s\n]*\((3|C)\)\s+([\s\S]*?)[\s\n]*\((4|D)\)\s+([\s\S]*)$/i,
      handler: (match: RegExpMatchArray) => {
        return {
          options: [match[2].trim(), match[4].trim(), match[6].trim(), match[8].trim()],
          matchedIndex: match.index!
        };
      }
    },
    // Style 2: 1) ... 2) ... 3) ... 4) ... or A) ... B) ... (C) ... (D) ...
    {
      regex: /[\s\n]*(1|A)\)\s+([\s\S]*?)[\s\n]*(2|B)\)\s+([\s\S]*?)[\s\n]*(3|C)\)\s+([\s\S]*?)[\s\n]*(4|D)\)\s+([\s\S]*)$/i,
      handler: (match: RegExpMatchArray) => {
        return {
          options: [match[2].trim(), match[4].trim(), match[6].trim(), match[8].trim()],
          matchedIndex: match.index!
        };
      }
    },
    // Style 3: 1. ... 2. ... 3. ... 4. ... or A. ... B. ...
    {
      regex: /[\s\n]*(1|A)\.\s+([\s\S]*?)[\s\n]*(2|B)\.\s+([\s\S]*?)[\s\n]*(3|C)\.\s+([\s\S]*?)[\s\n]*(4|D)\.\s+([\s\S]*)$/i,
      handler: (match: RegExpMatchArray) => {
        return {
          options: [match[2].trim(), match[4].trim(), match[6].trim(), match[8].trim()],
          matchedIndex: match.index!
        };
      }
    },
    // Style 4: [1] ... [2] ... [3] ... [4] ... or [A] ... [B] ...
    {
      regex: /[\s\n]*\[(1|A)\]\s+([\s\S]*?)[\s\n]*\[(2|B)\]\s+([\s\S]*?)[\s\n]*\[(3|C)\]\s+([\s\S]*?)[\s\n]*\[(4|D)\]\s+([\s\S]*)$/i,
      handler: (match: RegExpMatchArray) => {
        return {
          options: [match[2].trim(), match[4].trim(), match[6].trim(), match[8].trim()],
          matchedIndex: match.index!
        };
      }
    }
  ];

  for (const pattern of patterns) {
    const match = text.match(pattern.regex);
    if (match) {
      const { options, matchedIndex } = pattern.handler(match);
      
      let questionText = text.substring(0, matchedIndex).trim();
      questionText = questionText.replace(/[\s\n,;:]+$/, "");
      
      if (options.every(o => o.length > 0)) {
        const cleanedOptions = options.map(o => {
          let cleaned = o.trim();
          while (/^(?:[\n\r\s]+|\\n|\/n|\\\\n)/i.test(cleaned)) {
            cleaned = cleaned.replace(/^(?:[\n\r\s]+|\\n|\/n|\\\\n)/i, "").trim();
          }
          while (/(?:[\n\r\s]+|\\n|\/n|\\\\n)$/i.test(cleaned)) {
            cleaned = cleaned.replace(/(?:[\n\r\s]+|\\n|\/n|\\\\n)$/i, "").trim();
          }
          return cleaned;
        });
        return { questionText, options: cleanedOptions };
      }
    }
  }

  return null;
}
